---
title: "The Right Clubs"
type: "exercise"
description: "Using symbols, find the right golf clubs for you!"
tags: "arrays, symbols, golf"
visibility: "subscribe"
ignore:
- "solution.md"
- "the_right_clubs.md"
