---
title: "Golf Score Tabulator"
type: "exercise"
description: "Calculate your golf score using compound data structures"
tags: "compound data structures"
visibility: "subscribe"
ignore:
- "golf_score.md"
- "solution.md"
