---
title: "Voter Demographics"
type: "challenge"
description: "Use compound data structures to analyze voter data"
tags: "arrays, hashes, compound data structures"
visibility: "subscribe"
ignore:
- "voter_demographics.md"
- "solution.md"
