---
title: "Lunch at the Turn"
type: "exercise"
description: "Use hashes to determine the price of your lunch"
tags: "hashes, golf"
visibility: "subscribe"
ignore:
- "lunch_at_the_turn.md"
- "solution.md"
