---
title: "Grab Some Pizza!"
type: "exercise"
description: "Model your pizza order with a Ruby class"
tags: "class, initialize, objects, constructors, state, behavior, instance methods"
visibility: "subscribe"
---
